### PR TITLE
Categoryedit.php getOptions method Optimized

### PR DESCRIPTION
**Pull request by nadeeshaan**
Categoryedit.php getOptions method's query optimized by decomposing and removing group by and adding select distinct

### CODE REVIEW

**Comment by gunjanpatel** [comment]
### Test Results:

#### Before:

before1
before

#### After:

After1
After

**Comment by alikon** [comment]
send to joomlacms

**Comment by nadeeshaan** [comment]
## Testing Instructions:

In order to test this PR first apply the PR via the joomla Patch Test. Then log in to the admin panel and click on the add new article. After clicking on the add new article, the query executes.
Add New Article

### Original Query before the Optimization

``` sql
     SELECT a.id AS value, a.title AS text, a.level, a.published 
     FROM #_categories AS a 
     LEFT JOIN #_categories AS b 
     ON a.lft > b.lft 
     AND a.rgt < b.rgt 
     WHERE (a.extension = 'com_content') 
     AND a.published IN (0,1) 
     GROUP BY a.id, a.title, a.level, a.lft, a.rgt, a.extension, a.parent_id, a.published 
     ORDER BY a.lft ASC
```

### After the Optimization

``` sql
     SELECT DISTINCT c.id AS value, c.title AS text, c.level, c.published
      FROM (
                  SELECT DISTINCT id,title,level,published,parent_id,extension,lft,rgt 
                   FROM #_categories
                   WHERE  (extension = 'com_content') AND published IN (0,1)
                   ORDER BY lft ASC
                   ) AS c
      LEFT JOIN #_categories AS b
      ON x.lft > b.lft
      AND x.rgt < b.rgt
```

### Query Change Description

In the new query the change is the new sub select. In the previous query the tables are being joined and in the new query as you can see in the red color query is the sub select. In the sub select it filters the rows according to the `WHERE` clause of the previous query. As you can see this filters the rows and reduce the number of rows before the join and which results a fever number of rows to choose the attributes.Also Removed the group by clause and added the `SELECT DISTINCT` instead

**Comment by gunjanpatel** [comment]
@nadeeshaan Is this already sent to joomla-cms?

**Comment by nadeeshaan** [comment]
yes @gunjanpatel

**Comment by gunjanpatel** [comment]
Closing as it is already sent to joomla-cms.

**Pull request closed without merging**
