### PR TITLE
removed group by clause and added select distinct instead

### PR DESCRIPTION
**Pull request by nadeeshaan**
removed group by clause and added select distinct instead

### CODE REVIEW

**Comment by nadeeshaan** [comment]
Testing:
Query can be found : JROOT/libraries/cms/form/field/tag.php
In order to check the query execution log in to the admin console and click add new category. Then the query triggers.

Change in the Query: In this query group by clause has been removed and instead added the select distinct

**Comment by nadeeshaan** [comment]
## Testing Instructions:

In order to check the query execution log in to the admin console and click add new category. Then the query triggers.

addnewcat

### Original Query before the Optimization

``` sql
  SELECT a.id AS value, a.path, a.title AS text, a.level, a.published
  FROM ltzvy_tags AS a
  LEFT JOIN `ltzvy_tags` AS b 
  ON a.lft > b.lft 
  AND a.rgt < b.rgt
  WHERE `a`.`alias` <> 'root' 
  AND a.published IN (0,1)
  GROUP BY a.id, a.title, a.level, a.lft, a.rgt, a.parent_id, a.published, a.path
  ORDER BY a.lft ASC
```

### After the Optimization

``` sql
 SELECT DISTINCT a.id AS value, a.path, a.title AS text, a.level, a.published
  FROM ltzvy_tags AS a
  LEFT JOIN `ltzvy_tags` AS b 
  ON a.lft > b.lft 
  AND a.rgt < b.rgt
  WHERE `a`.`alias` <> 'root' 
  AND a.published IN (0,1)
  ORDER BY a.lft ASC
```

### Query Change Description

In this query `GROUP BY` clause has been removed and instead added the 'SELECT DISTINCT' clause in order to optimize the query execution

**Comment by alikon** [comment]
as per comment on https://github.com/joomla/joomla-cms/pull/4114
on JROOT\libraries\cms\form\field\tag.php
change line 138
`$query->where($db->quoteName('a.alias') . ' <> ' . $db->quote('root'));`
to
`$query->where($db->quoteName('a.lft') . ' > 0 ');`

**Comment by gunjanpatel** [comment]
@nadeeshaan Please add reference joomla-cms repo here.
Thanks.

**Comment by orware** [comment]
Comparing to the current file:
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/form/field/tag.php#L117

It looks like it has changed a bit since this pull request was made so I don't know if portions of the performance optimizations mentioned here are part of the current file already (it doesn't look exactly the same but I did see some parts that looked inspired by some of the code mentioned in this pull request).

**Comment by gunjanpatel** [comment]
Thanks @orware I will update master branch with latest code.

**Comment by gunjanpatel** [comment]
@orware It seems this PR is merged in Joomla! and that is why not able to see the difference and now having conflict after merge. So, leaving it closed. Here is a reference to Joomla! PR https://github.com/joomla/joomla-cms/pull/4114

**Pull request closed without merging**
