### PR TITLE
Added index to contentitem_tag_map table

### PR DESCRIPTION
**Pull request by nadeeshaan**
Index added to the #__contentitem_tag_map

### CODE REVIEW

**Comment by nadeeshaan** [comment]
Query:
SELECT `m`.`tag_id`,`t`.*

  FROM `#__contentitem_tag_map` AS m 

  INNER JOIN `#__tags` AS t  
  ON `m`.`tag_id` = `t`.`id`

  WHERE `m`.`type_alias` = 'com_content.article' 
  AND `m`.`content_item_id` = 5196 
  AND `t`.`published` = 1 
  AND t.access IN (1,1,5)

Testing:
In order to test this test this change you can use a fresh distribution and before you install add this PR. And then install. If you want to check with an already installed distribution you can add and index to the ('type_alias','content_item_id') field and then check how it works. For further clarification refer to the EXPLAIN statistics of the query too. At there look at the number of rows and index usage stats changes when having the index and without having the request

**Comment by alikon** [comment]
Remove the select star please

**Comment by alikon** [comment]
for testing on an installed site run this 1 sql line

`ALTER TABLE #__contentitem_tag_map ADD INDEX 'idx_alias_item_id' ('type_alias','content_item_id');`

**Comment by gunjanpatel** [comment]
Closing this as this is Merged in https://github.com/nadeeshaan/JGSoC-SQL-Optimisation/pull/29

**Pull request closed without merging**
