### PR TITLE
Added two sub string indexes to the session table

### PR DESCRIPTION
**Pull request by nadeeshaan**

### CODE REVIEW

**Comment by gunjanpatel** [comment]
@nadeeshaan Please provide testing instruction.

**Comment by nadeeshaan** [comment]
Testing:
Since this changes is applied in the installation folder it  cannot be tested in an installed site. For testing this change  need to follow either of the following
1. Add the indexes in the relevant fields in the database manually
2. Apply the patch in a new fork which has not installed and then test it after installing.
(Extremely sorry for the late description)

**Comment by alikon** [comment]
should be 
`PRIMARY KEY (`session_id`(32))`

**Comment by alikon** [comment]
for testing on an installed site run this 2 sql lines 

`ALTER TABLE #__session DROP PRIMARY KEY, ADD PRIMARY KEY(session_id(32));`

`ALTER TABLE #__session DROP INDEX time, ADD INDEX time(time(10));`

**Comment by gunjanpatel** [comment]
Closing this as this is Merged in https://github.com/nadeeshaan/JGSoC-SQL-Optimisation/pull/29

**Pull request closed without merging**
